db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://127.0.0.1:3306/ycsb?rewriteBatchedStatements=true
db.user=ycsb
db.passwd=ycsbpass

# table settings
db.table=usertable
fieldcount=100

# batching
jdbc.batchupdateapi=true
db.batchsize=100
jdbc.autocommit=false
